# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Portfolio Gohugo Theme"
license = "MIT"
licenselink = "https://github.com/bejnar/portfolio/blob/master/LICENSE.md"
description = "A Base theme for building full featured Hugo sites"
homepage = "https://github.com/bejnar/portfolio"
tags = ["website", "starter", "responsive", "Disqus", "blog", "Tachyons"]
features = ["posts", "shortcodes", "related content", "comments"]
min_version = 0.30.2

[author]
  name = "Roman Bejnar"
  homepage = "https://github.com/bejnar"